services:
  user_service_migrate:
    image: classified-service-main-app
    volumes:
      - ./src:/src
    environment:
      DB_URI: ${DB_URI}
      KAFKA_URI: ${KAFKA_URI}
    command: "alembic upgrade head"

    networks:
        - classified-service_default


networks:
  classified-service_default:
    external: true
