services:
  user_service_migrate:
    image: user-service-main-app
    volumes:
      - ./src:/src
    environment:
      DB_URI: ${DB_URI}
      REDIS_URI: ${REDIS_URI}
      KAFKA_URI: ${KAFKA_URI}
    command: "alembic upgrade head"
    # networks:
    #   - user_network


# networks:
#   user_network:
#     external: true
