version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ['--requirepass', '${REDIS_PASSWORD:?}']

volumes:
  redis_data:
